import sys
import matplotlib.pyplot as plt

# Worker counts used in the hardcoded baseline data below.
p = [1, 2, 4, 8, 16, 32]

# Fallback hardcoded times — used when no CSV is provided.
# Replace with your own measured values or run: bash run_tests.sh --benchmark
process_times = [
    130.26,   # P=1
    93.74,    # P=2
    54.34,    # P=4
    46.96,    # P=8
    55.52,    # P=16
    50.99     # P=32
]

thread_times = [
    179.75,   # P=1
    91.48,    # P=2
    49.62,    # P=4
    53.78,    # P=8
    55.14,    # P=16
    42.22     # P=32
]

# If a benchmark CSV is passed (generated by run_tests.sh --benchmark),
# read it and override the hardcoded times above.
if len(sys.argv) > 1:
    csv_file = sys.argv[1]
    proc_map = {}
    thr_map = {}
    with open(csv_file) as f:
        next(f)  # skip header row
        for line in f:
            mode, workers, seconds = line.strip().split(",")
            if mode == "process":
                proc_map[int(workers)] = float(seconds)
            elif mode == "thread":
                thr_map[int(workers)] = float(seconds)
    p = sorted(proc_map.keys())
    process_times = [proc_map[w] for w in p]
    thread_times  = [thr_map.get(w, None) for w in p]

# --- Plot 1: Raw wall-clock time ---
# --- Plot 2: Speedup (T1 / Tn) to illustrate Amdahl's law ---
fig, axes = plt.subplots(1, 2, figsize=(12, 5))

axes[0].plot(p, process_times, marker="o", label="ProcessTriangles")
axes[0].plot(p, thread_times,  marker="o", label="ThreadTriangles")
axes[0].set_xlabel("Number of Processes / Threads")
axes[0].set_ylabel("Real Time (seconds)")
axes[0].set_title("Process vs Thread Performance")
axes[0].grid(True)
axes[0].legend()

process_speedup = [process_times[0] / t for t in process_times]
thread_speedup  = [thread_times[0]  / t for t in thread_times]
ideal_speedup   = [w / p[0] for w in p]

axes[1].plot(p, process_speedup, marker="o", label="ProcessTriangles")
axes[1].plot(p, thread_speedup,  marker="o", label="ThreadTriangles")
axes[1].plot(p, ideal_speedup, linestyle="--", color="gray", label="Ideal (linear)")
axes[1].set_xlabel("Number of Processes / Threads")
axes[1].set_ylabel("Speedup (T1 / Tn)")
axes[1].set_title("Speedup — Amdahl's Law")
axes[1].grid(True)
axes[1].legend()

plt.tight_layout()
plt.savefig("test/performance.pdf", bbox_inches="tight")
print("Wrote test/performance.pdf")
